### ISSUE TITLE
Color scheme used for gdb

### ISSUE THREAD

**Issue by jstaursky** [Crypto-Cat/CTF#12]
What is your .gdbinit color settings? I like them more than the stock pwngdb/peda/gef ones

**Comment by Crypto-Cat** [comment]
It's not specific to GDB, just my terminal colour settings, here's the screenshot:

![image](https://user-images.githubusercontent.com/12751872/235374551-2cc94f32-61d2-44d5-9151-a1dcd38435ed.png)

I recommend keeping a default profile as well, since some tools have colour coded output, e.g. linpeas. You can easily swap between them with right click.

**Comment by jstaursky** [comment]
Hey thanks! BTW What is your `PS1` environment variable set to?

**Comment by Crypto-Cat** [comment]
```
if [ "$color_prompt" = yes ]; then
    PS1="\[\033[0;31m\]\342\224\214\342\224\200\$([[ \$? != 0 ]] && echo \"[\[\033[0;31m\]\342\234\227\[\033[0;37m\]]\342\224\200\")[$(if [[ ${EUID} == 0 ]]; then echo '\[\033[01;31m\]root\[\033[01;33m\]@\[\033[01;96m\]\h'; else echo '\[\033[0;39m\]\u\[\033[01;33m\]@\[\033[01;96m\]\h'; fi)\[\033[0;31m\]]\342\224\200[\[\033[0;32m\]\w\[\033[0;31m\]]\n\[\033[0;31m\]\342\224\224\342\224\200\342\224\200\342\225\274 \[\033[0m\]\[\e[01;33m\]\\$\[\e[0m\]"
else
    PS1='┌──[\u@\h]─[\w]\n└──╼ \$ '
fi```
